### PR TITLE
Filters everything that is below status code 500

### LINKED ISSUE #36: Erlang error %Phoenix.Router.NoRouteError reported on 404 after upgrade to plug_cowboy 2
After upgrade to plug_cowboy 2, 404 responses started to appear as errors in Bugsnag:

```
Erlang error: {{%Phoenix.Router.NoRouteError{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: [#Function<1.1812729/1 in Plug.Logger.call/2>], body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "fulfillment-staging.liefery.com", method: "GET", owner: #PID<0.2309.0>, params: %{}, path_info: ["css", "vendor.css"], path_params: %{}, port: 80, private: %{Fulfillment.Router => {[], %{}}, :phoenix_endpoint => Fulfillment.Endpoint, :phoenix_router => Fulfillment.Router, :plug_session_fetch => #Function<1.58261320/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {10, 10, 1, 5}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "text/css,*/*;q=0.1"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9,de;q=0.8"}

[redacted]
```

This didn't happen when using plug_cowboy 1.

It looks like multiple other libraries for error tracking services experienced the similar problem:
- https://github.com/appsignal/appsignal-elixir/issues/417
- https://github.com/getsentry/sentry-elixir/issues/328
- https://github.com/honeybadger-io/honeybadger-elixir/issues/193

I found the content in https://github.com/appsignal/appsignal-elixir/issues/417 particularly informative. [Here](https://github.com/appsignal/appsignal-elixir/issues/417#issuecomment-439876201) is the explanation and [here](https://github.com/appsignal/appsignal-elixir/issues/417#issuecomment-443695327) is a suggestion to switch from listening to Erlang's error_logger(which we do [here](https://github.com/liefery/bugsnex/blob/51b8aafacef99504cbfe6c5e29c473741530c1bd/lib/bugsnex.ex#L12)) to listening to Elixir's Logger.

We should investigate if the suggestion fixes the problem.

### PR DESCRIPTION
**Pull request by bitboxer**
This is how appsignal and others do the error handling in elixir.
Maybe there are use cases where the < 500 errors should be reported. If
there are, you can easily add your own error handlers for specific ones
or we need to modify the code here to make it configurable.

Ah and this PR also reformats using the elixir formatter. If you don't like it I will have to redo the PR and disable the auto format in my VS Code :trollface: .

closes #36

### CODE REVIEW

**Comment by bitboxer** [comment]
Ah and if you know how to build this in a way that older elixir/phoenix versions are still working and we have cowboy 2 in the tests, I am all 👂

File: mix.exs [hunk 1]
```diff
@@ -54,9 +54,9 @@ defmodule Bugsnex.Mixfile do
       {:httpoison, "~> 1.5.0"},
       {:poison, ">= 1.5.0"},
```
Comment (irmela) [inline mix.exs]: Would changing that to `{:poison, "~> 3.1.0"},` make it work for elixir < 1.6?

**Comment by bitboxer** [comment]
Sorry, I totally forgot to fix this PR 🦊 . Now it only has the minimal changes needed. After this is in, there will be another PR to do the `mix format` and maybe adding something that guarantees that the formatter is run. With `ex_check` for example.

**Comment by irmela** [comment]
Thanks a lot @bitboxer 💚

[I fixed the CI setup](#38) so if you rebase to the current master branch tests should pass.

**Comment by bitboxer** [comment]
Rebased. Let's see what the good old travis says.

**Comment by bitboxer** [comment]
Thank you for merging this so quickly.
